// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4WYx_Jrnt5B5tEwKjLfwxKEJfVfOWHP0',
    appId: '1:88340636882:web:e36267e34271b2a675390b',
    messagingSenderId: '88340636882',
    projectId: 'custom-roadmap-5af1f',
    authDomain: 'custom-roadmap-5af1f.firebaseapp.com',
    storageBucket: 'custom-roadmap-5af1f.appspot.com',
    measurementId: 'G-W3RE8H1LX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClaEvQtiXgANmEUjuhcAfoZqYu0e_somw',
    appId: '1:88340636882:android:792270e49c9c8f1275390b',
    messagingSenderId: '88340636882',
    projectId: 'custom-roadmap-5af1f',
    storageBucket: 'custom-roadmap-5af1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpFzrXJRXg2FTJ73OVdCY5zXnKRs7whI',
    appId: '1:88340636882:ios:be6f0c72fe3d31e675390b',
    messagingSenderId: '88340636882',
    projectId: 'custom-roadmap-5af1f',
    storageBucket: 'custom-roadmap-5af1f.appspot.com',
    iosBundleId: 'com.example.customRoadmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpFzrXJRXg2FTJ73OVdCY5zXnKRs7whI',
    appId: '1:88340636882:ios:be6f0c72fe3d31e675390b',
    messagingSenderId: '88340636882',
    projectId: 'custom-roadmap-5af1f',
    storageBucket: 'custom-roadmap-5af1f.appspot.com',
    iosBundleId: 'com.example.customRoadmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4WYx_Jrnt5B5tEwKjLfwxKEJfVfOWHP0',
    appId: '1:88340636882:web:f56aa8e3ac7dd2b675390b',
    messagingSenderId: '88340636882',
    projectId: 'custom-roadmap-5af1f',
    authDomain: 'custom-roadmap-5af1f.firebaseapp.com',
    storageBucket: 'custom-roadmap-5af1f.appspot.com',
    measurementId: 'G-YH97YVVLBK',
  );
}
